Logo #1056
smaranjitghose/doc2pen pull request #1072
Opened 2021-07-08 08:11 UTC by ishitakapoor26

Fixes #1056

2021-07-08 08:12 UTC, ishitakapoor26 commented
@AbhipsaGuru1012 pls review pr.

2021-07-08 17:00 UTC, smaranjitghose commented
Along with the gif could you please provide an SVG for the same?

2021-07-08 20:34 UTC, ishitakapoor26 commented
> Along with the gif could you please provide an SVG for the same?

yeah sure but animations won't work in svg format!

2021-07-08 21:52 UTC, smaranjitghose commented
> > Along with the gif could you please provide an SVG for the same?
> 
> yeah sure but animations won't work in svg format!

Ya, I know. This is basically for other places where we can't have a gif file. Also, update the favicon for the page with this

2021-07-09 08:09 UTC, ishitakapoor26 commented
I'm facing some issue in updating favicon to page, @AbhipsaGuru1012 can you please help?

2021-07-09 08:12 UTC, AbhipsaGuru1012 commented
> I'm facing some issue in updating favicon to page, @AbhipsaGuru1012 can you please help?

@ishitakapoor26 yes please let me know what issue you are facing

2021-07-12 08:26 UTC, smaranjitghose requested changes

2021-07-12 08:26 UTC, smaranjitghose commented on public/index.html
> +  <link rel="dynamic icon" id="favicon" href="src/assets/logo/DOC2PEN-favicon.gif" />
Update this in the seo component built using react-helmet

2021-07-20 09:37 UTC, Ayushparikh-code approved these changes

2021-07-24 03:28 UTC, anushbhatia commented
logo is too small so the text present inside is barely visible. Also in small devices it might not be that prominent so can you do something for that if possible.

2021-07-24 07:44 UTC, ishitakapoor26 commented
> logo is too small so the text present inside is barely visible. Also in small devices it might not be that prominent so can you do something for that if possible.

okay will make some changes to it!

2021-07-31 17:04 UTC, closed without merging