removed materialize
smaranjitghose/doc2pen pull request #217
Opened 2020-10-01 06:55 UTC by mharshita

@smaranjitghose sir i have removed materialize but there are some issues with editor page. Please review and suggest changes.

2020-10-01 06:59 UTC, mharshita commented
![image](https://user-images.githubusercontent.com/60281688/94777823-bdb1c080-03e1-11eb-848d-04c2cc3043ea.png)

2020-10-01 07:23 UTC, smaranjitghose commented
style.css should not be required for editor.html

2020-10-01 07:25 UTC, smaranjitghose commented
The alignment for Clan of Contributors and Project Maintainers is changed. Please fix it.
For each row, try to put 6 contributor cards in a single row

2020-10-01 07:26 UTC, smaranjitghose commented
SideNav is not working on Mobile view

2020-10-01 07:27 UTC, anushbhatia requested changes
You can use official navbar from bootstrap and change the colours to a little bit soothing

2020-10-01 07:27 UTC, anushbhatia commented on editor.html
> +    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossori
Keep only the latest version bootstrap and remove rest of it. It will be highly beneficially if the CSS and js are stored locally

2020-10-01 07:27 UTC, anushbhatia commented on editor.html
> +                    <a class="nav-link dropdown-toggle text-white main-text" href="#" id="navbarDropdown2" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
refer to the documentation of official dropdown from  bootstrap https://getbootstrap.com/docs/4.5/getting-started/introduction/

2020-10-01 07:27 UTC, smaranjitghose commented
Please delete the commented out code.

2020-10-01 07:33 UTC, mharshita commented
@smaranjitghose @anushbhatia Okay!

2020-10-01 12:56 UTC, smaranjitghose commented
Fantastic work @mharshita !

2020-10-01 12:57 UTC, merged

2020-10-02 02:07 UTC, mharshita commented
> Fantastic work @mharshita !

Thanks sir !