Updated contact form
smaranjitghose/doc2pen pull request #261
Opened 2020-10-06 18:43 UTC by himanshujaidka

2020-10-06 20:14 UTC, smaranjitghose requested changes

2020-10-06 20:14 UTC, smaranjitghose commented on editor.html
> +
Please pull the current changes to the codebase

2020-10-06 20:14 UTC, smaranjitghose commented on index.html
> +                            <p>Last Name *</p>
We already have the required attribute using HTML.

2020-10-06 20:15 UTC, smaranjitghose commented
The form is unresponsive. Please take care of that.

Adjust the captcha button accordingly so that on hovering over the feedback options it does not shift down ( An unpreferred UX)

2020-10-07 06:16 UTC, himanshujaidka commented
@smaranjitghose pls have a look in it

2020-10-07 06:18 UTC, closed without merging