Changed contact form UI
smaranjitghose/doc2pen pull request #264
Opened 2020-10-07 14:52 UTC by dipanshparmar

# changed contact form UI. 
Fixes #192 

## Before
![image](https://user-images.githubusercontent.com/49204837/95347514-9758bd00-08da-11eb-974a-88d4d304d496.png)

## After
![image](https://user-images.githubusercontent.com/49204837/95347573-aa6b8d00-08da-11eb-9d99-23780efb66ea.png)
![image](https://user-images.githubusercontent.com/49204837/95347623-b7887c00-08da-11eb-8404-90e34fd3cd4a.png)

2020-10-08 06:52 UTC, anushbhatia requested changes
![Doc2pen and 13 more pages - Personal - Microsoft​ Edge 08-10-2020 12_21_49](https://user-images.githubusercontent.com/40017559/95424817-e77a6280-0960-11eb-9240-331d65d2d718.png)

2020-10-08 07:15 UTC, dipanshparmar commented
@anushbhatia I fixed the bug. Please have a look now:
![image](https://user-images.githubusercontent.com/49204837/95426763-11815400-0964-11eb-93e4-5e36830c67b3.png)

2020-10-10 12:43 UTC, dipanshparmar commented
@smaranjitghose @anushbhatia

2020-10-10 18:34 UTC, smaranjitghose commented
> @anushbhatia I fixed the bug. Please have a look now:
> ![image](https://user-images.githubusercontent.com/49204837/95426763-11815400-0964-11eb-93e4-5e36830c67b3.png)

The emojis in the mobile view should be in a single line

2020-10-10 18:36 UTC, smaranjitghose commented
![contact_html](https://user-images.githubusercontent.com/46641503/95662583-92ec0880-0b55-11eb-9296-c4b4390e4184.jpg)

2020-10-11 04:15 UTC, dipanshparmar commented
@smaranjitghose Please have a look now:

![image](https://user-images.githubusercontent.com/49204837/95670250-73310080-0ba6-11eb-8a0d-a0695311591c.png)

2020-10-11 06:20 UTC, merged

2020-10-11 06:41 UTC, smaranjitghose commented on index.html
> -        <head>
Please do not mess up with the indentation of the parts of the code you are not working on

2020-10-11 06:42 UTC, smaranjitghose reviewed
Please ensure that you do not mess up indentation of other parts of the code you are not working on

2020-10-11 07:16 UTC, dipanshparmar commented
> Please ensure that you do not mess up indentation of other parts of the code you are not working on

Okay! I'll make sure from the next time :)