navbar hover effect added
smaranjitghose/doc2pen pull request #286
Opened 2020-12-22 10:41 UTC by shriyaMadan

2020-12-22 10:41 UTC, shriyaMadan commented
kindly review it

2020-12-22 18:33 UTC, anushbhatia commented
Add a minimal navigation don't use underline on hover effect

2020-12-22 18:34 UTC, anushbhatia requested changes
Add better javascript for animation

2020-12-27 10:37 UTC, merged

2020-12-27 14:58 UTC, shriyaMadan commented
What more changes are needed, I can remove the underline and put a background hover effect.