Add footer in REACT
smaranjitghose/doc2pen pull request #363
Opened 2021-01-08 18:39 UTC by neeagwl

#351

2021-01-09 14:38 UTC, anushbhatia requested changes
Two Minor changes I would Recommend 
1.For this import reacteasyemoji which was commented 
use  {emoji("Made with ❤️ in India for the students of the world.")} 
2. Use Black Colour for the footer don't follow the main project's gradient as of now.

2021-01-09 18:33 UTC, smaranjitghose requested changes

2021-01-09 18:33 UTC, smaranjitghose commented on .eslintcache
> +[{"C:\\Users\\agarw\\Desktop\\Web Development\\swoc\\doc2pen\\src\\index.js":"1","C:\\Users\\agarw\\Desktop\\Web Development\\swoc\\doc2pen\\src\\reportWebVitals.js":"2","C:\\Users\\agarw\\Desktop\\W
Remove this please

2021-01-09 18:34 UTC, smaranjitghose commented
> Two Minor changes I would Recommend
> 1.For this import reacteasyemoji which was commented
> use {emoji("Made with ❤️ in India for the students of the world.")}
> 2. Use Black Colour for the footer don't follow the main project's gradient as of now.
> 3. Bonus tip use proper names in the className so that it will be easy for other's to understand it.

++. Code Readability is must!

2021-01-10 16:42 UTC, neeagwl commented
I tried to make the requested changes. Please review it.

2021-01-13 13:20 UTC, merged

2021-01-13 13:22 UTC, smaranjitghose commented
![](https://media.giphy.com/media/3oz8xAFtqoOUUrsh7W/giphy.gif)
Nice work!