navigation bar added in header
smaranjitghose/doc2pen pull request #392
Opened 2021-01-13 15:37 UTC by RitikPandey1

Issue #350

2021-01-14 18:45 UTC, smaranjitghose commented on .eslintcache
> +[{"E:\\open source project\\doc2pen\\src\\index.js":"1","E:\\open source project\\doc2pen\\src\\App.js":"2","E:\\open source project\\doc2pen\\src\\reportWebVitals.js":"3","E:\\open source project\\d
Remove this

2021-01-15 06:39 UTC, RitikPandey1 commented on .eslintcache
> +[{"E:\\open source project\\doc2pen\\src\\index.js":"1","E:\\open source project\\doc2pen\\src\\App.js":"2","E:\\open source project\\doc2pen\\src\\reportWebVitals.js":"3","E:\\open source project\\d
@smaranjitghose  done

2021-01-17 17:12 UTC, anushbhatia requested changes
Convert navbar link to black and then will merge it.

2021-01-17 17:13 UTC, anushbhatia reviewed
After this we will add the home page then you can make the routing part of it

2021-01-18 06:09 UTC, RitikPandey1 commented
> Convert navbar link to black and then will merge it.

@anushbhatia  done 👍

2021-01-18 16:12 UTC, merged