#599 and #601 done
smaranjitghose/doc2pen pull request #617
Opened 2021-03-14 07:12 UTC by shreyanema33

Added new pages and scrollBar added to the editor.

2021-03-14 17:59 UTC, smaranjitghose requested changes

2021-03-14 17:59 UTC, smaranjitghose commented on src/pages/Editor/containers/editContext.js
> +    Diary2: "diary2.jpg"
Only add the new files, Do not tamper with the existing ones

2021-03-14 18:11 UTC, anushbhatia commented
Add the scroll bar on the home page and the editor page, not inside the editor that looks weird and not really helpful.

2021-03-15 07:19 UTC, anushbhatia requested changes
Resolve the conflict and also add blue colour to the scrollbar so that it resembles our theme and keep the scrollbar uniform on all pages

2021-03-16 02:08 UTC, smaranjitghose commented
## Feedback:
- Diary2 is similar to Ruled4. We don't need that
- Blank2 is irrelevant for this scenario.

Please do a squash commit and raise a new PR following the contribution guidelines carefully

2021-03-16 02:08 UTC, closed without merging