Form UI changed
smaranjitghose/doc2pen pull request #719
Opened 2021-03-18 07:40 UTC by Rohit-Parameswaran

Closes #677 
### Changes:
- Increased relative width of experience form
- Added animations to the emoji ratings
- Made a small change to the message textarea for uniformity

### Screenshot
**Before:**
![image](https://user-images.githubusercontent.com/53703467/111589576-06700100-87eb-11eb-8bef-613b83bb4d2d.png)
**After:**
![](https://cdn.discordapp.com/attachments/802814842759151640/822000644885184512/unknown.png)

2021-03-18 15:36 UTC, anushbhatia requested changes

2021-03-18 15:36 UTC, anushbhatia commented on src/pages/Home/sections/Contact/components/ExperienceForm/ExpForm.module.css
> +  width: 40vw;
if you are using px everywhere maintain it here too.

2021-03-18 15:36 UTC, anushbhatia commented on src/pages/Home/sections/Contact/components/EmojiRating/EmojiRating.module.css
> +  transform: rotate(360deg) scale(1.5);
avoid transforming 360 deg animation instead use grow property with ease in animation that would look more appealing and minimal.

2021-03-19 07:34 UTC, Rohit-Parameswaran commented
I have made the requested changes

2021-03-19 19:51 UTC, merged