added github logo and animations
smaranjitghose/doc2pen pull request #773
Opened 2021-03-27 07:26 UTC by lopeselio

made changes to PR #761 .... 
-[x] I have added loop animation to the logo as suggested, used  https://useanimations.com/ to implement it.

![file](https://user-images.githubusercontent.com/43913734/112713563-c51ed600-8efb-11eb-9be1-4c4c708be1f3.gif)

2021-03-27 07:52 UTC, smaranjitghose commented
## Feedback:

- Please do the following change as well

![home_page](https://user-images.githubusercontent.com/46641503/112714245-6eb39680-8eff-11eb-8901-21013c0e924d.png)

2021-03-27 07:55 UTC, lopeselio commented
You mean I have to remove the entire subscribe to our newsletter section code along with the enter your email text box ?

2021-03-27 07:59 UTC, smaranjitghose commented
> @smaranjitghose You mean I have to remove the entire subscribe to our newsletter section code along with the enter your email text box ?

Yes

2021-03-27 08:22 UTC, lopeselio commented
> > @smaranjitghose You mean I have to remove the entire subscribe to our newsletter section code along with the enter your email text box ?
> 
> Yes

![image](https://user-images.githubusercontent.com/43913734/112715017-91e04500-8f03-11eb-95f5-e76807c9abf4.png)
How does it look ?

2021-03-27 08:54 UTC, lopeselio commented
changes have been made

2021-03-27 09:48 UTC, anushbhatia requested changes
![image](https://user-images.githubusercontent.com/40017559/112716977-b2ae9780-8f0f-11eb-9861-597d9cff119f.png)
It is not completely centre aligned.

2021-03-27 11:44 UTC, lopeselio commented
@anushbhatia @smaranjitghose changes pushed as requested 
![image](https://user-images.githubusercontent.com/43913734/112719627-cd890800-8f1f-11eb-91fc-69a8d11c0b35.png)

2021-03-28 03:56 UTC, lopeselio commented
Hey @anushbhatia, I have pushed changes to the branch as suggested.

2021-03-28 04:40 UTC, merged

2021-03-28 10:13 UTC, smaranjitghose commented on src/components/Footer/Footer.js
> +// import {FaEnvelope} from "react-icons/fa";
Please do not comment unused code for this project. Simply remove it