Custom File name Feature
smaranjitghose/doc2pen pull request #781
Opened 2021-03-27 10:25 UTC by nishant23122000

## Current behaviour
Till now, we have only a dropdown to select the file type which user wants to download and when we click on the option provided on the dropdown then file downloaded automatically and the name of the is always **generate**

## Expected behaviour
Now as I mention in issue #780 , we have a new feature to add custom filename. check below steps

step 1: Click on the download button on the top section, the dialog box will open
step 2:  in the dialog box enter the file name that you want 
step 3: Select the file type that you want to download like pdf or png
step 4: Click on the download button at the bottom of the dialog
step 5 : you will see that file downloaded with you the custom filename

https://user-images.githubusercontent.com/53515714/112717690-5437e800-8f14-11eb-8829-103d0e4d6503.mp4

## Exception situation:
There is also error handling if the user download the file without providing the filename

PS :  You can see the current filetype which have a * appended

2021-03-28 04:07 UTC, anushbhatia requested changes
Also, check why the build is failing.

2021-03-28 04:07 UTC, anushbhatia commented on src/pages/Editor/sections/Settings/DownloadFileModal.js
> +                                style={{ backgroundColor: fileType == file ? "#103f5f" : "#6666FF" }}
use ===

2021-03-28 04:07 UTC, anushbhatia commented on src/pages/Editor/sections/Settings/DownloadFileModal.js
> +import { Button, Modal, ModalBody, ModalFooter } from 'reactstrap';
here modal, modal body and modal footer aren't used remove them.

2021-03-28 05:00 UTC, nishant23122000 commented
Hey @anushbhatia  now it's done, please check it

2021-03-28 10:20 UTC, smaranjitghose commented
## Feeback:

- Modify the UI as shown in the image below

![Download_UI_Change](https://user-images.githubusercontent.com/46641503/112748978-0fc44f00-8fdd-11eb-9778-5585a1efdbbf.png) 

     - The Cancel button can be removed from the bottom and placed on the top with a X button
     - Changing the helper text to "What would you like to call the file?"
     - Make the text above the buttons : "Export as:"

2021-03-28 10:21 UTC, smaranjitghose commented
@anushbhatia perhaps you could give some deeper insights into the UI aspect

2021-03-28 12:24 UTC, nishant23122000 commented
Hey @smaranjitghose I think this close button looks pretty good compare to the close button before and also I change the color of the buttons to the theme color of website

2021-03-29 03:14 UTC, smaranjitghose commented
@nishant23122000 LGTM! Could you please pull the recent updates and incorporate them into your PR to fix the merge conflicts. The rest of it is awesome brother!

2021-03-29 04:54 UTC, nishant23122000 commented
Hey, @smaranjitghose  I think now the conflict is solved and thanks

2021-03-29 21:59 UTC, merged

2021-03-29 21:59 UTC, smaranjitghose commented
Nice work @nishant23122000 !

2021-03-30 05:38 UTC, nishant23122000 commented
@smaranjitghose  Than you😎