Improve the Form UI of the Contact Section @Home Page
smaranjitghose/doc2pen pull request #789
Opened 2021-03-27 18:56 UTC by samidha28

Fixes #677 
Changes:
- Modified the background color and position of circles
- Changed the header and placeholder text
- Increased space between input fields for uniformity
- Changed styling of input fields and textarea when having focus
- Changed the styling of send button

Screenshot:
Before:
![Screenshot (173)](https://user-images.githubusercontent.com/58340748/112731196-dac3e800-8f5b-11eb-80f5-6990607b47cf.png)
After:
![Screenshot (174)](https://user-images.githubusercontent.com/58340748/112731216-f16a3f00-8f5b-11eb-8b40-990f0e04b72c.png)

2021-03-28 09:38 UTC, iamdarshshah commented on src/pages/Home/sections/Contact/components/ExperienceForm/ExperienceForm.jsx
> +      {/*<h2>Contact us your query or just send a hello.</h2>*/}
```suggestion
```
Remove this.

2021-03-28 09:42 UTC, iamdarshshah requested changes
@samidha28 Placeholder text should not include `?` in it. It should be updated everywhere it has been used.

2021-03-28 10:11 UTC, smaranjitghose commented
> Fixes #677
> Changes:
> 
> * Modified the background color and position of circles
> * Changed the header and placeholder text
> * Increased space between input fields for uniformity
> * Changed styling of input fields and textarea when having focus
> * Changed the styling of send button
> 
> Screenshot:
> Before:
> ![Screenshot (173)](https://user-images.githubusercontent.com/58340748/112731196-dac3e800-8f5b-11eb-80f5-6990607b47cf.png)
> After:
> ![Screenshot (174)](https://user-images.githubusercontent.com/58340748/112731216-f16a3f00-8f5b-11eb-8b40-990f0e04b72c.png)

Remove the shapes from the background of the form. @anushbhatia could you please assist with the choice of color palette for it as well as the send button

2021-03-28 13:05 UTC, samidha28 commented
@iamdarshshah I re-requested review but it's not showing for some reason. I'll work on further changes @anushbhatia please provide suggestions .

2021-03-29 17:47 UTC, anushbhatia reviewed
1. https://dribbble.com/shots/14126196-Contact-Form-01
2. https://dribbble.com/shots/14139115-Contact-Form-02
3. https://dribbble.com/shots/14595041-Daily-UI-028

2021-04-01 14:44 UTC, closed without merging