404Page
smaranjitghose/doc2pen pull request #808
Opened 2021-03-29 19:22 UTC by padmajabhol

![Screenshot (88)](https://user-images.githubusercontent.com/75530516/112888638-3b852900-90f2-11eb-9312-36d0d016d895.png)
Changed UI of the page.

2021-03-29 19:28 UTC, anushbhatia requested changes
could be better if related to our project

2021-03-29 19:31 UTC, padmajabhol commented
> could be better if related to our project

By changing the neon green to the color?

2021-03-29 21:50 UTC, smaranjitghose commented
404 page is not loading. Check the deploy [preview](https://deploy-preview-808--doc2pen.netlify.app/404) please

2021-03-29 21:51 UTC, smaranjitghose commented on src/pages/404/notFound.module.css
> +
Avoid adding extra whitespaces between lines

2021-03-29 21:52 UTC, smaranjitghose commented
Use react-spring to make a custom animation.

There should be a button to go back to Home Page as well

2021-03-30 22:48 UTC, smaranjitghose commented
> > Use react-spring to make a custom animation.
> > There should be a button to go back to Home Page as well
> 
> Please provide me a little more time so I can redesign the page as per your web app's theme.

Sure. Take 2 more days. If required, we can extend further

2021-04-13 19:27 UTC, smaranjitghose commented
Closed due to inactivity

2021-04-13 19:27 UTC, closed without merging