Update README.md
smaranjitghose/doc2pen pull request #812
Opened 2021-03-30 11:13 UTC by RubenFalcao14

I have added the required full stops at various places in the read.me

2021-03-30 22:22 UTC, smaranjitghose requested changes

2021-03-30 22:22 UTC, smaranjitghose commented on README.md
> +# Doc2Pen.
This is a heading😅

2021-03-30 22:22 UTC, smaranjitghose commented on README.md
> +## DEMO.
This is a sub-heading😅

2021-03-30 22:22 UTC, smaranjitghose commented on README.md
> +- [React - Dropzone.js](https://react-dropzone.js.org/): Drag and drop file uploads.
This is a list + Comments

2021-03-30 22:22 UTC, closed without merging

2021-03-30 22:23 UTC, smaranjitghose commented
PR not relevant

2021-03-31 00:17 UTC, RubenFalcao14 commented
Sorry 😓