Converted all reactstrap and bootstrap related code to react-bootstrap
smaranjitghose/doc2pen pull request #827
Opened 2021-04-01 10:11 UTC by AshuKV

Fixes #800

2021-04-01 14:44 UTC, anushbhatia commented on package.json
> +    "react-bootstrap": "^1.5.2",
remove the boostrap

2021-04-01 14:45 UTC, anushbhatia requested changes
```
src/components/Dropdown/Dropdown.js
3:44:54 PM:   Line 4:3:  'DropdownToggle' is defined but never used  no-unused-vars
3:44:54 PM:   Line 5:3:  'DropdownMenu' is defined but never used    no-unused-vars
3:44:54 PM:   Line 6:3:  'DropdownItem' is defined but never used    no-unused-vars
3:44:54 PM: src/pages/Editor/sections/Settings/DownloadFileModal.js
3:44:54 PM:   Line 2:25:  'ModalBody' is defined but never used    no-unused-vars
3:44:54 PM:   Line 2:36:  'ModalFooter' is defined but never used  no-unused-vars

```

Deploy is faling here too please check.

2021-04-04 09:39 UTC, AshuKV reviewed
I have reviewed the changes. The PR can be merged now.

2021-04-14 18:00 UTC, anushbhatia commented
Resolve the conflicts

2021-04-18 14:30 UTC, closed without merging